### PR TITLE
Added rounding to shadow container and removed -1px.

### PR DESCRIPTION
**Pull request by braxtonCoats**
## PR Checklist

Check these before submitting your pull request:

- [x] Visual and behavioral components are separated
- [x] Exported components are documented with examples
- [x] Props have JSDoc comments
- [x] All relevant visual sub-components can be overridden via props
- [x] Any extra props are spread into the outermost rendered element

## Breaking Changes

Removed styling that points out its used for browser quirks. While working on these changes I didn't notice anything odd around the shadows rendering

## Changes to Existing Components

Added border rounding and extended heading and separating lines to reach the end of the table.

Screen Shot 2019-04-10 at 3 34 24 PM

### CODE REVIEW

**Comment by a-type** [comment]
The reason that hack was there was so that the right internal shadow would show up. Can you verify that the right internal shadow is present when there is more table content beyond the right border?

**Comment by braxtonCoats** [comment]
Screen Shot 2019-04-18 at 11 11 05 AM
 
Table shadow still shows when there is content outside of the visible area

**Comment by a-type** [comment]
Looks good, but which browser are you using? Have you tried others?

**Comment by braxtonCoats** [comment]
Yea, just tested edge, IE and firefox (mac and windows) and all look good.

**Pull request merged**
