### PR TITLE
Ui 575 security fix

### PR DESCRIPTION
**Pull request by tato123**
## PR Checklist

Check these before submitting your pull request:

- [ ] Visual and behavioral components are separated
- [ ] Exported components are documented with examples
- [ ] Props have JSDoc comments
- [ ] All relevant visual sub-components can be overridden via props
- [ ] Any extra props are spread into the outermost rendered element

## Breaking Changes

_To be verified_

## Changes to Existing Components

Changes to package dependencies

## New Visual Components

No new visual components created

## New Behavioral Components

No new behavioral components created

### CODE REVIEW

**Comment by zelitzsi** [comment]
👍 for locking versions

**Comment by tato123** [comment]
Good catch, I actually just ran `npm audit fix` and checked in the fixes. passing this along to @denysYefremov  to finish

**Comment by Aubron** [comment]
> Also, can we just lock all these versions in general?

I miss yarn

**Comment by denysYefremov** [comment]
when you run `npm audit fix` it updates only the packages which do not contain breaking changes. The only way to update packages which contain breaking changes is update them manually 1 by 1, or run `npm audit fix --force`. 

So if @tato123 didn't run the `npm audit fix --force` then there shouldn't be any problem with the packages.

I ran `npm run build` and `npm run start` and all build successfully

**Pull request merged**
